# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PBUtils' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBUtils

  target 'PBUtilsTests' do
    # Pods for testing
  end

end

target 'PBUtilsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBUtilsExample
  pod 'PBUtils', :path => '../.'

end
